; this is an autogenerated assembly file
; it is not designed to be human readable. if possible, read the .ocar file that generated it.
; == generated via Ocar == https://www.github.com/Mher-DeLight/Ocar ==
asdiqisj ; direct conversion
