#include "../include/IrGenerator.h"

// == HELPERS ==
void ocarlang::IrGenerator::load_ast(std::unique_ptr<ScopeBlock> ast) {
    entry_point = std::move(ast);
}
std::vector<std::unique_ptr<ocarlang::Ir>> ocarlang::IrGenerator::give_ir() {
    return std::move(ir);
}

void ocarlang::IrGenerator::generate_ir() {
    entry_point->accept(*this);
}
void ocarlang::IrGenerator::print_ir(std::ostream& stream) {
    for (auto& irnode : ir) {
        irnode->print(stream);
        stream << "\n";
    }
}
std::string ocarlang::IrGenerator::generateLabel() {
    return "autogeneratedLabel__ocarLang" +
           std::to_string(
               labelCounter++); // weird name to decrease collision with user-defined labels
}

// == VISIT ==
void ocarlang::IrGenerator::visit(ScopeBlock& node) {
    for (auto& child : node.children) {
        child->accept(*this);
    }
};
void ocarlang::IrGenerator::visit(StringLiteral& node) {

};
void ocarlang::IrGenerator::visit(FloatLiteral& node) {};
void ocarlang::IrGenerator::visit(IntegerLiteral& node) {
    currentNode = std::make_unique<IrIntLit>(node.number);
};
void ocarlang::IrGenerator::visit(BooleanLiteral& node) {};
void ocarlang::IrGenerator::visit(VoidLiteral& node) {};
void ocarlang::IrGenerator::visit(VariableDefinition& node) {
    node.memory->accept(*this);
    auto memory =
        get_current_as<IrMemName>("internal, expected node.memory to convert to IrMemName");

    node.value->accept(*this);
    std::unique_ptr<ocarlang::IrExpr> expression = get_current_as<ocarlang::IrExpr>();
    ir.push_back(std::make_unique<IrMovStmt>(std::move(memory), std::move(expression)));
};
void ocarlang::IrGenerator::visit(BinaryExpression& node) {};
void ocarlang::IrGenerator::visit(RoutineCallExpr& node) {};
void ocarlang::IrGenerator::visit(VariableReference& node) {
    currentNode = std::make_unique<IrMemName>(node.name);
};
void ocarlang::IrGenerator::visit(UnaryExpression& node) {};
void ocarlang::IrGenerator::visit(VariableReassignment& node) {
    node.memory->accept(*this);
    auto memory = get_current_as<IrMemName>(
        "internal, expected variableReassignment.memory to convert to IrMemName");

    node.value->accept(*this);
    std::unique_ptr<ocarlang::IrExpr> expression = get_current_as<ocarlang::IrExpr>();
    ir.push_back(std::make_unique<IrMovStmt>(std::move(memory), std::move(expression)));
};
void ocarlang::IrGenerator::visit(RoutineCallStmt& node) {
    ir.push_back(std::make_unique<IrRtnCall>(node.identifier));
};
void ocarlang::IrGenerator::visit(RoutineDefinition& node) {
    std::string endLabel = generateLabel();
    ir.push_back(std::make_unique<IrJmp>(
        endLabel)); // a jump so the function isn't accidentally ran depending on the placement
    ir.push_back(std::make_unique<IrLabelStmt>(node.identifier));
    node.scope->accept(*this);
    if (node.hasRet)
        ir.push_back(std::make_unique<IrRetStmt>());
    ir.push_back(std::make_unique<IrLabelStmt>(endLabel));
};
void ocarlang::IrGenerator::visit(SectionDefinition& node) {
    ir.push_back(std::make_unique<IrSection>(node.identifier));
}
void ocarlang::IrGenerator::visit(Global& node) {
    ir.push_back(std::make_unique<IrGlobal>(node.identifier));
}
void ocarlang::IrGenerator::visit(RoutineDeclaration& node) {}
void ocarlang::IrGenerator::visit(AsmInstruction& node) {
    ir.push_back(std::make_unique<IrAsm>(node.instruction));
}
void ocarlang::IrGenerator::visit(DeleteSymbol& node) {}
void ocarlang::IrGenerator::visit(FreeMemory& node) {}
void ocarlang::IrGenerator::visit(IfStatement& node) {
    std::string jumpName = condMap.at(node.cond);
    std::string trueLabel = generateLabel();
    std::string endLabel = generateLabel();

    ir.push_back(std::make_unique<IrJmp>(trueLabel, jumpName));
    ir.push_back(std::make_unique<IrJmp>(endLabel));
    ir.push_back(std::make_unique<IrLabelStmt>(trueLabel));
    node.scope->accept(*this);
    ir.push_back(std::make_unique<IrLabelStmt>(endLabel));
};
void ocarlang::IrGenerator::visit(Compare& node) {
    node.left->accept(*this);
    auto left = get_current_as<IrMemName>();

    node.right->accept(*this);
    auto right = get_current_as<IrExpr>();

    ir.push_back(std::make_unique<IrCmp>(std::move(left), std::move(right)));
}
void ocarlang::IrGenerator::visit(RegisterName& node) {
    currentNode = std::make_unique<IrMemName>(node.name);
}
void ocarlang::IrGenerator::visit(SyscallStatement& node) {
    ir.push_back(std::make_unique<IrSyscall>());
}
void ocarlang::IrGenerator::visit(ArithmeticOperation& node) {
    node.left->accept(*this);
    auto left = get_current_as<IrMemName>("expected left to be a memory name");

    node.right->accept(*this);
    auto right = get_current_as<IrExpr>("expected right to be a memory name");

    using BO = BinaryOperation;
    std::unique_ptr<IrOp> op;
    switch (node.operation) {
        case BO::ADD:
            op = std::make_unique<IrAdd>(std::move(left), std::move(right));
            break;
        case BO::SUBTRACT:
            op = std::make_unique<IrSub>(std::move(left), std::move(right));
            break;
        case BO::MULTIPLY:
            op = std::make_unique<IrImul>(std::move(left), std::move(right));
            break;
        default:
            break;
    }
    if (!op) {
        panic("Invalid binary operation at " + std::to_string(node.location.row) + ":" +
              std::to_string(node.location.column));
    }
    ir.push_back(std::move(op));
}
void ocarlang::IrGenerator::visit(RawAssignment& node) {
    node.left->accept(*this);
    auto left = get_current_as<IrMemName>();

    node.right->accept(*this);
    auto right = get_current_as<IrExpr>();

    ir.push_back(std::make_unique<IrMovStmt>(std::move(left), std::move(right)));
}
void ocarlang::IrGenerator::visit(RawLabel& node) {
    ir.push_back(std::make_unique<IrLabelStmt>(node.labelname));
}
void ocarlang::IrGenerator::visit(JumpStatement& node) {
    ir.push_back(std::make_unique<IrJmp>(node.labelname, "jmp"));
}
void ocarlang::IrGenerator::visit(WhileLoop& node) {
    std::string startLabel = generateLabel();
    std::string continueLabel = generateLabel();
    std::string endLabel = generateLabel();
    std::string jumpName = condMap.at(node.cond);

    ir.push_back(std::make_unique<IrLabelStmt>(startLabel));
    node.comparison->accept(*this);
    ir.push_back(std::make_unique<IrJmp>(continueLabel, jumpName));
    ir.push_back(std::make_unique<IrJmp>(endLabel, "jmp"));
    ir.push_back(std::make_unique<IrLabelStmt>(continueLabel));
    node.scope->accept(*this);
    ir.push_back(std::make_unique<IrJmp>(startLabel, "jmp"));
    ir.push_back(std::make_unique<IrLabelStmt>(endLabel));
}
void ocarlang::IrGenerator::visit(SwapStatement& node) {
    node.left->accept(*this);
    auto left =
        get_current_as<IrMemName>("expected swaps statement left to be a valid ir memory name");

    node.right->accept(*this);
    auto right =
        get_current_as<IrMemName>("expected swaps statement right to be a valid ir memory name");

    ir.push_back(std::make_unique<IrXchg>(std::move(left), std::move(right)));
}
